[MozillaCACerts]
git-tree-sha1 = "b7a1f1e9763de643a400ffb49283712c80cad5cb"

    [[MozillaCACerts.download]]
    sha256 = "5d9c07edc92d80c318304169eee4e22708a009d94cdc180da0024903e45de0b6"
    url = "https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2021.1.19+0/MozillaCACerts.v2021.1.19.any.tar.gz"
