[MozillaCACerts]
git-tree-sha1 = "ea7ce7c368e63d513a2df1b27c4514e9e385832f"

    [[MozillaCACerts.download]]
    sha256 = "2faa628ca2ad126f22c9acf6d8554d812e2125a5029b86de5ad2f0029039ab9c"
    url = "https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2024.3.11+0/MozillaCACerts.v2024.3.11.any.tar.gz"
