[MozillaCACerts]
git-tree-sha1 = "55b90c0ce41f9153ecb780ca5f4911a25f19815d"

    [[MozillaCACerts.download]]
    sha256 = "b78354b39dac0452498db4930ecdc61d90d9ed0ccec4fa50aec734ec9ca7b5af"
    url = "https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2026.7.16+0/MozillaCACerts.v2026.7.16.any.tar.gz"
