[MozillaCACerts]
git-tree-sha1 = "63d506697dc8cdbaea9fdc0383503dd7bc3a2ff8"

    [[MozillaCACerts.download]]
    sha256 = "735c2be82de55d43acea472426dfb5998cbaefb1329d4dcf4513a4de02c8b670"
    url = "https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2020.10.14+0/MozillaCACerts.v2020.10.14.any.tar.gz"
