[MozillaCACerts]
git-tree-sha1 = "66e161682ab1784a3e1cf6308e795db09c79664d"

    [[MozillaCACerts.download]]
    sha256 = "c38d56e016ea9848a0af8e0dadd90c8ee3cf0539e87a24be667e71e95d0ec8bb"
    url = "https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2022.3.29+0/MozillaCACerts.v2022.3.29.any.tar.gz"
