[MozillaCACerts]
git-tree-sha1 = "c1ad0be38cba7de7c935cde435818fb8a1af00b1"

    [[MozillaCACerts.download]]
    sha256 = "bf8f4adea811d455bbaa24bb69cc544128ec5e87c21e346473b05671533a1558"
    url = "https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2024.7.2+0/MozillaCACerts.v2024.7.2.any.tar.gz"
