[MozillaCACerts]
git-tree-sha1 = "b9426fe58f49fb59d2ec2b359b8638e9d2f3c26f"

    [[MozillaCACerts.download]]
    sha256 = "5f79debc613ae682eece454562377cfd0eafc57b9a32c5c45e624d7cbb1bc1a7"
    url = "https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2023.1.10+0/MozillaCACerts.v2023.1.10.any.tar.gz"
