[MozillaCACerts]
git-tree-sha1 = "c1da49f3cf75dc5b6cf46adf861307aa31c47f91"

    [[MozillaCACerts.download]]
    sha256 = "3257493b47f666a882ccc795260818e8bdd230bccac9cdaab8316c08e11a1880"
    url = "https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2023.12.12+0/MozillaCACerts.v2023.12.12.any.tar.gz"
