[MozillaCACerts]
git-tree-sha1 = "19ae438e71b736a7efbbcbba4e5cf5c5bb9849e5"

    [[MozillaCACerts.download]]
    sha256 = "ca9adf6f27e1fce112ad52ee77bcd9d242c2cfbdfc9bcda65db51592795ebf98"
    url = "https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2025.5.20+0/MozillaCACerts.v2025.5.20.any.tar.gz"
