[MozillaCACerts]
git-tree-sha1 = "5d645de4effaabaa78669c61f7b00a7b53d25442"

    [[MozillaCACerts.download]]
    sha256 = "9ca49d2eb904c2732cbeaca84500cae1c711673f5f945c9bb8838348022bddd6"
    url = "https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2023.8.22+0/MozillaCACerts.v2023.8.22.any.tar.gz"
