[MozillaCACerts]
git-tree-sha1 = "688d0c7254d28767ce3aee3fdc6b55b1df21bed9"

    [[MozillaCACerts.download]]
    sha256 = "c7cc2d27ec1ae28b9ce2d8669ae051f987b1dbf9d1fcc8e536a1e7a6a1a2b97f"
    url = "https://github.com/JuliaBinaryWrappers/MozillaCACerts_jll.jl/releases/download/MozillaCACerts-v2022.2.1+0/MozillaCACerts.v2022.2.1.any.tar.gz"
