# Autogenerated wrapper script for MozillaCACerts_jll for any
export cacert

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"
LIBPATH_default = ""

# Relative path to `cacert`
const cacert_splitpath = ["share", "cacert.pem"]

# This will be filled out by __init__() for all products, as it must be done at runtime
cacert_path = ""

# cacert-specific global declaration
# This will be filled out by __init__()
cacert = ""


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"MozillaCACerts")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    global cacert_path = normpath(joinpath(artifact_dir, cacert_splitpath...))

    global cacert = cacert_path
    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(vcat(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ':')

    
end  # __init__()

